fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    group:
        group_class:   FOS\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    from_email:
        address: test@test.com
        sender_name: test@test.com
